# Generated by Django 5.2.8 on 2025-12-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('shopping', 'Shopping'), ('food', 'Food'), ('home', 'Home'), ('transport', 'Transport'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
